# Form implementation generated from reading ui file 'gui\components\workspace_creation_widget.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(402, 256)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prefix_text_browser = QtWidgets.QTextBrowser(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prefix_text_browser.sizePolicy().hasHeightForWidth())
        self.prefix_text_browser.setSizePolicy(sizePolicy)
        self.prefix_text_browser.setMinimumSize(QtCore.QSize(350, 35))
        self.prefix_text_browser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.prefix_text_browser.setFont(font)
        self.prefix_text_browser.setAutoFillBackground(False)
        self.prefix_text_browser.setStyleSheet("QTextBrowser {\n"
"        background: transparent;\n"
"        border: none;\n"
"    }")
        self.prefix_text_browser.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.prefix_text_browser.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.prefix_text_browser.setLineWidth(0)
        self.prefix_text_browser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.prefix_text_browser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.prefix_text_browser.setObjectName("prefix_text_browser")
        self.horizontalLayout_2.addWidget(self.prefix_text_browser)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.continue_button = QtWidgets.QPushButton(parent=Form)
        self.continue_button.setObjectName("continue_button")
        self.horizontalLayout_8.addWidget(self.continue_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 11, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.welcome_label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.welcome_label.setFont(font)
        self.welcome_label.setObjectName("welcome_label")
        self.horizontalLayout.addWidget(self.welcome_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.key_line_edit = QtWidgets.QLineEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_line_edit.sizePolicy().hasHeightForWidth())
        self.key_line_edit.setSizePolicy(sizePolicy)
        self.key_line_edit.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.key_line_edit.setFont(font)
        self.key_line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.key_line_edit.setObjectName("key_line_edit")
        self.horizontalLayout_5.addWidget(self.key_line_edit)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.echo_toggle_button = QtWidgets.QPushButton(parent=Form)
        self.echo_toggle_button.setMinimumSize(QtCore.QSize(23, 23))
        self.echo_toggle_button.setMaximumSize(QtCore.QSize(23, 23))
        self.echo_toggle_button.setText("")
        self.echo_toggle_button.setCheckable(True)
        self.echo_toggle_button.setObjectName("echo_toggle_button")
        self.horizontalLayout_6.addWidget(self.echo_toggle_button)
        self.random_key_button = QtWidgets.QPushButton(parent=Form)
        self.random_key_button.setMinimumSize(QtCore.QSize(23, 23))
        self.random_key_button.setMaximumSize(QtCore.QSize(23, 23))
        self.random_key_button.setText("")
        self.random_key_button.setObjectName("random_key_button")
        self.horizontalLayout_6.addWidget(self.random_key_button)
        self.copy_to_clipboard_button = QtWidgets.QPushButton(parent=Form)
        self.copy_to_clipboard_button.setMinimumSize(QtCore.QSize(23, 23))
        self.copy_to_clipboard_button.setMaximumSize(QtCore.QSize(23, 23))
        self.copy_to_clipboard_button.setBaseSize(QtCore.QSize(23, 23))
        self.copy_to_clipboard_button.setText("")
        self.copy_to_clipboard_button.setObjectName("copy_to_clipboard_button")
        self.horizontalLayout_6.addWidget(self.copy_to_clipboard_button)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.postfix_text_browser = QtWidgets.QTextBrowser(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postfix_text_browser.sizePolicy().hasHeightForWidth())
        self.postfix_text_browser.setSizePolicy(sizePolicy)
        self.postfix_text_browser.setMinimumSize(QtCore.QSize(350, 105))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.postfix_text_browser.setFont(font)
        self.postfix_text_browser.setAutoFillBackground(False)
        self.postfix_text_browser.setStyleSheet("QTextBrowser {\n"
"        background: transparent;\n"
"        border: none;\n"
"    }")
        self.postfix_text_browser.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.postfix_text_browser.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.postfix_text_browser.setLineWidth(0)
        self.postfix_text_browser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.postfix_text_browser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.postfix_text_browser.setObjectName("postfix_text_browser")
        self.horizontalLayout_7.addWidget(self.postfix_text_browser)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 10, 0, 1, 1)
        self.key_label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.key_label.setFont(font)
        self.key_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.key_label.setObjectName("key_label")
        self.gridLayout_2.addWidget(self.key_label, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Workspace Creation"))
        self.prefix_text_browser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">As this seems to be your first time running the Omniverse application on this computer, we\'ll need you to set up an encryption key for security purposes.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.continue_button.setText(_translate("Form", "Continue"))
        self.welcome_label.setText(_translate("Form", "Welcome to the Omniverse"))
        self.echo_toggle_button.setToolTip(_translate("Form", "Toggle Visibility"))
        self.random_key_button.setToolTip(_translate("Form", "Generate Random Key"))
        self.copy_to_clipboard_button.setToolTip(_translate("Form", "Copy to Clipboard"))
        self.postfix_text_browser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The encryption key plays a crucial role in safeguarding your data and files. Keep it private and stored securely. If you suspect that your key is compromised, an admin user should change it promptly. We recommend changing your encryption key periodically to ensure optimum security.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Keep in mind, if the encryption key is lost, it\'s not recoverable and all access to encrypted data will be lost.</span></p></body></html>"))
        self.key_label.setText(_translate("Form", "Encryption Key (Length: 44):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
