# Form implementation generated from reading ui file 'src\gui\components\blueprint_controls_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(158, 469)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.language_model_label = QtWidgets.QLabel(parent=Form)
        self.language_model_label.setObjectName("language_model_label")
        self.verticalLayout_3.addWidget(self.language_model_label)
        self.language_model_combo_box = QtWidgets.QComboBox(parent=Form)
        self.language_model_combo_box.setObjectName("language_model_combo_box")
        self.verticalLayout_3.addWidget(self.language_model_combo_box)
        self.protocol_label = QtWidgets.QLabel(parent=Form)
        self.protocol_label.setObjectName("protocol_label")
        self.verticalLayout_3.addWidget(self.protocol_label)
        self.protocol_combo_box = QtWidgets.QComboBox(parent=Form)
        self.protocol_combo_box.setObjectName("protocol_combo_box")
        self.verticalLayout_3.addWidget(self.protocol_combo_box)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.temperature_label = QtWidgets.QLabel(parent=Form)
        self.temperature_label.setObjectName("temperature_label")
        self.verticalLayout_4.addWidget(self.temperature_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.temperature_slider = QtWidgets.QSlider(parent=Form)
        self.temperature_slider.setMaximum(20)
        self.temperature_slider.setProperty("value", 1)
        self.temperature_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.temperature_slider.setObjectName("temperature_slider")
        self.horizontalLayout.addWidget(self.temperature_slider)
        spacerItem2 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.sentiment_browser = QtWidgets.QTextBrowser(parent=Form)
        self.sentiment_browser.setObjectName("sentiment_browser")
        self.verticalLayout_2.addWidget(self.sentiment_browser)
        self.entity_browser = QtWidgets.QTextBrowser(parent=Form)
        self.entity_browser.setObjectName("entity_browser")
        self.verticalLayout_2.addWidget(self.entity_browser)
        self.summary_browser = QtWidgets.QTextBrowser(parent=Form)
        self.summary_browser.setObjectName("summary_browser")
        self.verticalLayout_2.addWidget(self.summary_browser)
        self.knowledge_browser = QtWidgets.QTextBrowser(parent=Form)
        self.knowledge_browser.setObjectName("knowledge_browser")
        self.verticalLayout_2.addWidget(self.knowledge_browser)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.language_model_label.setText(_translate("Form", "Language Model:"))
        self.protocol_label.setText(_translate("Form", "Protocol:"))
        self.temperature_label.setText(_translate("Form", "Temperature: 0.1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
